# Generated by Django 5.2.5 on 2025-08-11 04:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogapp', '0003_alter_post_user_user_reg_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_by',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
