# Generated by Django 5.2.5 on 2026-03-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogapp', '0009_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_by',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
